In [ ]:
%load_ext autoreload
%autoreload 2

In [1]:
import numpy as np

In [2]:
a = np.zeros((3,1))
a

array([[0.],
       [0.],
       [0.]])

In [5]:
a[0,0] = 1
a[1,0] = 2
a[2,0] = 3
a

array([[1.],
       [2.],
       [3.]])

In [10]:
(3 == a) * (3== a)

array([[False],
       [False],
       [ True]])